apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vmonitor-metric-agent.secretconfigname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vmonitor-metric-agent.labels" . | nindent 4 }}
type: Opaque
data:
  CLUSTER_NAME: {{ default "cluter-k8s" .Values.vmonitor.clusterName | b64enc | quote }}
  IAM_CLIENT_ID: {{ default "YOUR_IAM_CLIENT_ID" .Values.vmonitor.iamClientID | b64enc | quote }}
  IAM_CLIENT_SECRET: {{ default "YOUR_IAM_CLIENT_SECRET" .Values.vmonitor.iamClientSecret | b64enc | quote }}
  VMONITOR_SITE: {{ default "monitoring-agent.vngcloud.vn" .Values.vmonitor.vmonitorSite | b64enc | quote }}
  IAM_URL: {{ default "https://iamapis.vngcloud.vn/accounts-api/v2/auth/token" .Values.vmonitor.iamURL | b64enc | quote }}
  INFLUX_USER: {{ default "default" .Values.vmonitor.influxUser | b64enc | quote }}
  INFLUX_PASSWORD: {{ default "defaultpassword" .Values.vmonitor.influxPassword | b64enc | quote }}