apiVersion: v2
appVersion: 1.1.3
name: vngcloud-blockstorage-csi-driver
description: A Helm chart for VngCloud BlockStorage CSI Driver
version: 0.0.3
kubeVersion: ">=1.17.0-0"
home: https://github.com/vngcloud/vngcloud-blockstorage-csi-driver
sources:
  - https://github.com/vngcloud/vngcloud-blockstorage-csi-driver
keywords:
  - vngcloud
  - blockstorage
  - csi
maintainers:
  - name: VngCloud
    url: https://github.com/vngcloud/vngcloud-blockstorage-csi-driver