{{- if and .Values.certRenewal.enabled .Values.certRenewal.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd-manager.certRenewal.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "etcd-manager.certRenewal.labels" . | nindent 4 }}
type: Opaque
stringData:
  telegram-bot-token: {{ .Values.certRenewal.secrets.telegramBotToken | quote }}
  telegram-chat-id: {{ .Values.certRenewal.secrets.telegramChatId | quote }}
{{- end }}