{{- if and .Values.certChecker.enabled .Values.certChecker.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etcd-manager.fullname" . }}-cert-checker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "etcd-manager.certChecker.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "etcd-manager.fullname" . }}-cert-checker
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-manager.certChecker.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}