{{- if and .Values.certChecker.enabled .Values.certChecker.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etcd-manager.certChecker.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "etcd-manager.certChecker.labels" . | nindent 4 }}
  {{- with .Values.certChecker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}