{{- if and .Values.certRenewal.enabled .Values.certRenewal.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etcd-manager.certRenewal.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "etcd-manager.certRenewal.labels" . | nindent 4 }}
  {{- with .Values.certRenewal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}