{{- if and .Values.certChecker.enabled .Values.certChecker.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "etcd-manager.fullname" . }}-cert-checker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "etcd-manager.certChecker.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  {{- with .Values.certChecker.rbac.extraRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}