{{- if and .Values.certRenewal.enabled .Values.certRenewal.rbac.create .Values.certRenewal.rbac.createClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.certRenewal.rbac.clusterRoleName }}
  labels:
    {{- include "etcd-manager.certRenewal.labels" . | nindent 4 }}
rules:
  - apiGroups: ["kamaji.clastix.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
{{- end }}