{{- if and .Values.certRenewal.enabled .Values.certRenewal.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etcd-manager.fullname" . }}-cert-renewal
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "etcd-manager.certRenewal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "etcd-manager.fullname" . }}-cert-renewal
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-manager.certRenewal.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}