{{- if and .Values.certRenewal.enabled .Values.certRenewal.rbac.create .Values.certRenewal.rbac.createClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.certRenewal.rbac.clusterRoleName }}-binding
  labels:
    {{- include "etcd-manager.certRenewal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.certRenewal.rbac.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "etcd-manager.certRenewal.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}